### ISSUE TITLE
java --version

### ISSUE THREAD

**Issue by taruch** [aldettinger/camel-quarkus-workshop#15]
Current directions say to use java --version to check version:

On RHEL 8, this doesn't work:
[truch@truch ~]$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

On RHEL 8, this does work:
[truch@truch ~]$ java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (build 25.332-b09, mixed mode)

**Comment by aldettinger** [comment]
Ok @taruch. `java -version` is working on my machine too. So I've aligned to this.
Many thanks for reporting :+1:
