### ISSUE TITLE
Switch from Redpanda to Strimzi as default testcontainer image

### ISSUE THREAD

**Issue by fvaleri** [aldettinger/camel-quarkus-workshop#18]
I think it would be better to use the Strimzi testcontainer image by default, as it includes the official implementation of the Kafka APIs.

https://github.com/strimzi/test-container-images

https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaDevServicesBuildTimeConfig.java#L30-L49

**Comment by aldettinger** [comment]
@fvaleri Is it like already done as a side effect ? like we had it for free while migrating to quarkus 3 ?
Or maybe, it's not needed anymore ?

**Comment by fvaleri** [comment]
@aldettinger sorry for not adding a reason for closing. I still see Redpanda as default, so after a year and no feedback I decided to close it. That's fine. Feel free to reopen it if you have user feedback on that.

**Comment by aldettinger** [comment]
Understood, thanks @fvaleri
