### ISSUE TITLE
Quarkus compile did not succeed

### ISSUE THREAD

**Issue by manfredmuth** [aldettinger/camel-quarkus-workshop#24]
A change README is attached.
Reason for the issue was missing javac on the execution node

[README.md](https://github.com/user-attachments/files/17679141/README.md)

**Comment by aldettinger** [comment]
Many thanks @manfredmuth , see how it's fixed here with special kudos ;)
https://github.com/aldettinger/camel-quarkus-workshop/commit/d1fd74524036a40b3e0f6f64e031dd940c9ee604
