### ISSUE TITLE
`mvn -f part-*-jvm-mode/pom.xml clean quarkus:dev` does not work on Windows

### ISSUE THREAD

**Issue by ppalaga** [aldettinger/camel-quarkus-workshop#6]
```
C:\orgs\cq\camel-quarkus-workshop>mvn -f part-*-jvm-mode/pom.xml clean quarkus:dev
POM file "part-*-jvm-mode/pom.xml" specified the -f/--file command-line argument does not exist
```

^ this happens in `cmd.exe`

**Comment by ppalaga** [comment]
... while it works in Git Bash. 

But it runs only the `part-2-jvm-mode` module - was that the intention? - Souldn't we better instruct them to run `mvn -f part-2-jvm-mode/pom.xml clean quarkus:dev` ? That would work in all shells.

Maybe we should also tell the users to exit the dev mode by `CTRL-C`?

**Comment by aldettinger** [comment]
@ppalaga I don't think we could expect all the commands to work on Linux/MAC and Windows. There are more examples.
In this case, it's easy and fix upstream https://github.com/aldettinger/camel-quarkus-workshop/commit/5c52c3e6329e2a106bb5667ffe747f12355860cd.

**Comment by ppalaga** [comment]
Thanks, much better now for Windows users.
